vault:
  global:
    tlsDisable: false
  server:
    dev:
      enabled: false
    standalone:
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 0
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-secret/helm-vault.pem"
          tls_key_file  = "/vault/userconfig/vault-secret/helm-vault-key.pem"
        }
        storage "file" {
          path = "/vault/data"
        }
    extraEnvironmentVars:
      VAULT_CACERT: /vault/userconfig/vault-secret/ca.pem
    extraVolumes:
    - type: secret
      name: vault-secret
