apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
data:
  helm-vault.pem: |-
    {{ .Files.Get "ssl/helm-vault.pem" | b64enc }}
  helm-vault-key.pem: |-
    {{ .Files.Get "ssl/helm-vault-key.pem" | b64enc }}
  ca.pem: |-
    {{ .Files.Get "ssl/ca.pem" | b64enc }}